### ISSUE TITLE
Add support for custom strings in Device Flow

### ISSUE THREAD

**Issue by alfredovaldes** [cli/oauth#25]
On the device flow, add support to specify the message to be shown to the user.

On oauth_device.go, currently the messages are:
`fmt.Fprintf(stdout, "First, copy your one-time code: %s\n", code.UserCode)`
`fmt.Fprint(stdout, "Then press [Enter] to continue in the web browser... ")`

**Comment by mislav** [comment]
Hi, if you need custom strings, then just copy the implementation of `func DeviceFlow()` into your app and change any details that you like! That function was just meant to be a reference implementation anyway.
