### ISSUE TITLE
Can I create an access token with SSO enabled?

### ISSUE THREAD

**Issue by mfcollins3** [cli/oauth#5]
I'm trying to create a CLI tool for internal use at my company that can access an internal repository in our GitHub Enterprise Cloud organization (we have SSO enabled). I can use this library to successfully create an access token for my account, but I can't use the access token to access my repository. Is it possible to request that the access token have SSO enabled programmatically so that I can use it to hit an internal repository, or would I be better off just asking my users to provide a personal access token with SSO already enabled?

**Comment by mislav** [comment]
@mfcollins3 While the user is authorizing your OAuth app in their web browser, there should be offered a list of organizations that require SSO that the user can additionally authorize the token for. Does that not appear for users of your app?

**Comment by mfcollins3** [comment]
Looks like it was my error. Thanks for the response.
