### ISSUE TITLE
Recommended flow for refreshing token?

### ISSUE THREAD

**Issue by jghiloni** [cli/oauth#67]
Hi! I'd like to be able to log in with the device flow and store the token in a file, along with the refresh token. If the access token is expired, I'd like to refresh. Is there a way to do that with this library? I'm trying to avoid the oauth2 module, as it's more than I need, as I will be doing pure git operations with the go-git module.

If that's what I gotta do, so be it, but if there's something I'm missing that sure would be neat 😃

**Comment by jtmcg** [comment]
Hey @jghiloni, this module is for supporting the auth flow for `gh` only. However, I think we've got what you're looking to do built in natively to the CLI. [gh auth](https://cli.github.com/manual/gh_auth) and in particular `gh auth token` will output the tokens used for logging in, so you don't have to save it to a file yourself, and `gh auth status` can check the authentication state for each host you've connected to, essentially checking for expiration. Perhaps you could built what you need using those tools? Unless I'm missing something...

**Comment by jtmcg** [comment]
Alright, I'm going to answer your questions one at a time:

> I'd like to be able to log in with the device flow and store the token in a file, along with the refresh token

The [DeviceFlow function](https://github.com/cli/oauth/blob/adf5f733ffd14993aad9f3ff02c757a737f7c63b/oauth_device.go#L18) returns an auth token, so you may be able to interface with that directly for your use case. Maybe the [example for device flow](https://github.com/cli/oauth/blob/adf5f733ffd14993aad9f3ff02c757a737f7c63b/device/examples_test.go) would be helpful

Note, the access token follows this [struct](https://github.com/cli/oauth/blob/adf5f733ffd14993aad9f3ff02c757a737f7c63b/api/access_token.go#L4-L13), which also contains the refresh token

> If the access token is expired, I'd like to refresh

I'm not sure how to tell if the token is expired... I think this is usually managed by whatever is granting the token. You'll likely need to build something specific to handle that part of this.


If you're interfacing with GitHub, then the CLI tool can do most of this for you. The [`gh auth` command set](https://cli.github.com/manual/gh_auth) may solve your problems out of the box.
